M48
; DRILL file {KiCad (6.0.7)} date Mon Sep  5 18:06:54 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-09-05T18:06:54-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0413
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0512
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0720
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C0.1260
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T5C0.1299
%
G90
G05
T1
X3.42Y-5.6967
T2
X3.42Y-5.4033
T3
X4.9351Y-3.9113
X5.1351Y-3.9113
T4
X3.05Y-3.95
X5.885Y-6.65
X6.0Y-3.95
T5
X5.0351Y-4.2113
T0
M30
